--SET DATABASE UNIQUE NAME icedms;
INSERT INTO SYS_USER (CREATION_DATE, CREATION_USER, EMAIL, FIRST_NAME, LAST_NAME, MODIFICATION_DATE, MODIFICATION_USER, PASSWORD, PSEUDO) 
	VALUES ('2015-05-26', 'admin', 'admin@icesoft.ch', 'Enea', 'Bette', NULL, NULL, 'password', 'admin');
INSERT INTO MIMETYPE (CODE, DESCRIPTION, ISO_CODE) 
	VALUES ('PDF', 'Portable Document Format', 'application/pdf');
INSERT INTO INDEX_TYPE (CODE, DESCRIPTION, VALIDATION_RULE) 
	VALUES ('BILLNO', 'Bill number', '[0-9]+');
INSERT INTO INDEX_TYPE (CODE, DESCRIPTION, VALIDATION_RULE) 
	VALUES ('USER', 'Nickname of the person using the application', '[a-zA-Z0-9_-]+');
INSERT INTO INDEX_TYPE (CODE, DESCRIPTION, VALIDATION_RULE) 
	VALUES ('PERSON', 'Concatenation of first and last name of the person', '[a-zA-Zéèòüöà-]+');
INSERT INTO DOCUMENT_LANGUAGE (CODE, DESCRIPTION, ISO_CODE) 
	VALUES ('it', 'Italiano Svizzera', 'it_CH');
INSERT INTO DOCUMENT_LANGUAGE (CODE, DESCRIPTION, ISO_CODE) 
	VALUES ('f', 'Francese Svizzera', 'fr_CH');
INSERT INTO DOCUMENT_LANGUAGE (CODE, DESCRIPTION, ISO_CODE) 
	VALUES ('d', 'Tedesco Svizzera', 'de_CH');
INSERT INTO DOCUMENT_GROUP (CODE, CREATION_DATE, CREATION_USER, DESCRIPTION, MODIFICATION_DATE, MODIFICATION_USER) 
	VALUES ('MAN', '2015-05-26', 'admin', 'Management', NULL, NULL);
INSERT INTO DOCUMENT_GROUP (CODE, CREATION_DATE, CREATION_USER, DESCRIPTION, MODIFICATION_DATE, MODIFICATION_USER) 
	VALUES ('PROD', '2015-05-26', 'admin', 'Production', NULL, NULL);
INSERT INTO DOCUMENT_GROUP (CODE, CREATION_DATE, CREATION_USER, DESCRIPTION, MODIFICATION_DATE, MODIFICATION_USER) 
	VALUES ('ACC', '2015-05-26', 'admin', 'Accounting', NULL, NULL);
INSERT INTO DOCUMENT_TYPE (CODE, CREATION_DATE, CREATION_USER, DESCRIPTION, MODIFICATION_DATE, MODIFICATION_USER) 
	VALUES ('BILL', '2015-05-26', 'admin', 'Bills', '2015-05-26', NULL);
INSERT INTO DOCUMENT_TYPE (CODE, CREATION_DATE, CREATION_USER, DESCRIPTION, MODIFICATION_DATE, MODIFICATION_USER) 
	VALUES ('ORDER', '2015-05-26', 'admin', 'Orders', '2015-05-26', NULL);
INSERT INTO DOCUMENT_TYPE (CODE, CREATION_DATE, CREATION_USER, DESCRIPTION, MODIFICATION_DATE, MODIFICATION_USER) 
	VALUES ('BULL', '2015-05-26', 'admin', 'Bulletin', '2015-05-26', NULL);
INSERT INTO DOCUMENT_TYPE_DOCUMENT_GROUP (DOCUMENT_TYPE_ID, DOCUMENT_GROUP_ID) 
	VALUES (1, 3);
INSERT INTO DOCUMENT_TYPE_DOCUMENT_GROUP (DOCUMENT_TYPE_ID, DOCUMENT_GROUP_ID) 
	VALUES (2, 1);
INSERT INTO DOCUMENT_TYPE_DOCUMENT_GROUP (DOCUMENT_TYPE_ID, DOCUMENT_GROUP_ID) 
	VALUES (3, 1);
INSERT INTO INDEX_TYPE_DOCUMENT_TYPE (MANDATORY, MULTIVALUED, DOCUMENT_TYPE_ID, INDEX_TYPE_ID) 
	VALUES (1, 0, 1, 1);
INSERT INTO INDEX_TYPE_DOCUMENT_TYPE (MANDATORY, MULTIVALUED, DOCUMENT_TYPE_ID, INDEX_TYPE_ID) 
	VALUES (1, 0, 1, 2);
INSERT INTO INDEX_TYPE_DOCUMENT_TYPE (MANDATORY, MULTIVALUED, DOCUMENT_TYPE_ID, INDEX_TYPE_ID) 
	VALUES (0, 0, 1, 3);
INSERT INTO DOCUMENT (ARCHIVE_DATE, CONFIDENTIAL, CREATION_DATE, CREATION_USER, LAST_REVISION, MODIFICATION_DATE, MODIFICATION_USER, "NAME", STATUS, DOCUMENT_TYPE_ID, LANGUAGE_ID) 
	VALUES ('2025-05-26', 0, '2015-05-26', 'admin', '0.1', '2015-05-26', NULL, 'test-document', 'NEW', 1, 1);
INSERT INTO DOCUMENT_VERSION (CONTENT, CREATION_DATE, CREATION_USER, LOCK_TIME, MAX_LOCK_TIME, MODIFICATION_DATE, MODIFICATION_USER, REVISION_NUMBER, DOCUMENT_ID, LOCK_USER_ID, MIMETYPE_ID) 
	VALUES (NULL, '2015-05-26', 'admin', NULL, NULL, '2015-05-26', NULL, '0.1', 1, NULL, 1);
INSERT INTO DOCUMENT_INDEX (TEXT_VALUE, INDEX_TYPE_ID, DOCUMENT_ID)
        VALUES('50494943', 1, 1);
INSERT INTO DOCUMENT_INDEX (TEXT_VALUE, INDEX_TYPE_ID, DOCUMENT_ID)
        VALUES('pippo', 2, 1);
--INSERT INTO DOCUMENT_INDEX (TEXT_VALUE, INDEX_TYPE_ID, DOCUMENT_ID)
--        VALUES('Enea Bette', 1, 3);